# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c4232ff460a821d66d0b1b9a77bd9cc269b0595d03f4de105bf040641b768241187ed9a47c7232f6afb208ecc32cd7c9394f97885fc078cda4cd8261f7426e

test:
  secret_key_base: 4ae37c50d04e216bf3199c8fe704097664368d02671e3c6cbdb2953e56414de99e791367809bb8a67c9a3ca05ad19c2f56adcec6fb40b1c01464435ede131dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
